import React, { useState, useEffect } from "react";
import { ArrowUp, ArrowDown, Search, Loader2, Activity, LayoutDashboard, Target } from "lucide-react";
import { API_BASE } from "../api_config";

export default function PredictionTableView() {
  const [predictions, setPredictions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [search, setSearch] = useState("");
  const [sortConf, setSortConf] = useState(null);

  useEffect(() => {
    let cancelled = false;
    const fetchPreds = async () => {
      try {
        const res = await fetch(`${API_BASE}/api/market/predictions`);
        if (!res.ok) throw new Error("Failed to fetch predictions");
        const data = await res.json();
        if (!cancelled) setPredictions(data.predictions || []);
      } catch (err) {
        if (!cancelled) setError(err.message);
      } finally {
        if (!cancelled) setLoading(false);
      }
    };
    fetchPreds();
    const id = setInterval(fetchPreds, 15000);
    return () => { cancelled = true; clearInterval(id); };
  }, []);

  let filtered = predictions.filter(p => p.ticker.toLowerCase().includes(search.toLowerCase()));
  if (sortConf === "asc") filtered.sort((a, b) => a.confidence - b.confidence);
  if (sortConf === "desc") filtered.sort((a, b) => b.confidence - a.confidence);

  return (
    <div className="flex-1 overflow-y-auto w-full p-4 md:p-6 lg:p-8 max-w-[1440px] mx-auto animate-fade-in">
       {/* Page Header */}
       <div className="flex flex-col gap-2 mb-6">
          <div className="flex items-center gap-3">
             <LayoutDashboard size={20} className="text-[var(--accent)]" />
             <h1 className="heading-1">Model Predictions</h1>
          </div>
          <p className="text-[13px] text-[var(--text-muted)]">Live directional consensus generated by the intelligence network.</p>
       </div>

       {/* Toolbar Area */}
       <div className="flex flex-col sm:flex-row gap-4 mb-6 justify-between items-center bg-[var(--card-bg)] p-4 rounded-[var(--radius-lg)] border border-[var(--border-color)] shadow-sm">
          <div className="relative w-full sm:w-64">
             <input
               value={search}
               onChange={e => setSearch(e.target.value)}
               placeholder="Search ticker..."
               className="input-standard pl-9"
             />
             <Search size={14} className="absolute left-3 top-2.5 text-[var(--text-muted)]" />
          </div>

          <div className="flex items-center gap-3 text-[12px] w-full sm:w-auto">
             <span className="font-medium text-[var(--text-muted)] hidden sm:inline">Sort Confidence:</span>
             <div className="toggle-group w-full sm:w-auto justify-between">
                <button onClick={() => setSortConf(null)} className={`toggle-item ${sortConf === null ? "active" : ""}`}>Default</button>
                <button onClick={() => setSortConf("desc")} className={`toggle-item ${sortConf === "desc" ? "active" : ""}`}>Highest</button>
                <button onClick={() => setSortConf("asc")} className={`toggle-item ${sortConf === "asc" ? "active" : ""}`}>Lowest</button>
             </div>
          </div>
       </div>

       {/* Content Area */}
       {loading && predictions.length === 0 ? (
         <div className="h-64 flex flex-col items-center justify-center gap-4 bg-[var(--card-bg)] border border-[var(--border-color)] rounded-[var(--radius-lg)]">
           <Loader2 size={24} className="text-[var(--accent)] animate-spin" />
           <span className="text-[12px] font-medium text-[var(--text-muted)]">Loading model outputs...</span>
         </div>
       ) : error ? (
         <div className="h-64 flex flex-col items-center justify-center gap-2 bg-[var(--card-bg)] border border-[var(--border-color)] rounded-[var(--radius-lg)] text-[var(--negative)]">
            <Target size={24} className="mb-2" />
            <p className="font-semibold text-[13px]">Prediction Feed Offline</p>
            <p className="text-[11px] font-mono opacity-80">{error}</p>
         </div>
       ) : (
         <div className="bg-[var(--card-bg)] border border-[var(--border-color)] rounded-[var(--radius-lg)] shadow-sm overflow-hidden overflow-x-auto">
           <table className="table-standard min-w-[700px]">
             <thead>
               <tr>
                 <th className="w-1/6">Asset</th>
                 <th className="w-1/6 text-right">Price</th>
                 <th className="w-1/6 text-center">Direction</th>
                 <th className="w-1/4">Confidence</th>
                 <th className="w-1/6 text-right">Target</th>
               </tr>
             </thead>
             <tbody>
               {filtered.map(row => {
                 const isBull = row.direction === "BULLISH";
                 const color = isBull ? "var(--positive)" : "var(--negative)";
                 const Icon = isBull ? ArrowUp : ArrowDown;
                 return (
                   <tr key={row.ticker}>
                     <td>
                        <div className="flex flex-col">
                           <span className="font-semibold text-white">{row.ticker}</span>
                           <span className="text-[11px] text-[var(--text-muted)]">{row.name.length > 20 ? row.name.slice(0,20)+"..." : row.name}</span>
                        </div>
                     </td>
                     <td className="text-right font-mono text-[13px]">
                        ${row.current_price?.toFixed(2)}
                     </td>
                     <td className="text-center">
                        <span 
                           className="inline-flex items-center gap-1.5 px-2 py-0.5 rounded-[var(--radius-sm)] text-[10px] font-bold tracking-wider"
                           style={{ backgroundColor: `${color}15`, color, border: `1px solid ${color}30` }}
                        >
                           <Icon size={12} /> {row.direction}
                        </span>
                     </td>
                     <td>
                        <div className="flex items-center gap-3">
                           <div className="flex-1 h-2 bg-[#1e232b] rounded-full overflow-hidden">
                              <div className="h-full rounded-full transition-all duration-700" style={{ width: `${row.confidence}%`, backgroundColor: color }} />
                           </div>
                           <span className="font-mono text-[11px] w-10 text-right">{row.confidence}%</span>
                        </div>
                     </td>
                     <td className="text-right font-mono text-[13px] font-medium text-white">
                        ${row.target_price?.toFixed(2)}
                     </td>
                   </tr>
                 );
               })}
               {filtered.length === 0 && (
                 <tr>
                   <td colSpan={5} className="text-center py-8 text-[12px] text-[var(--text-muted)]">
                     No predictions match current filters.
                   </td>
                 </tr>
               )}
             </tbody>
           </table>
         </div>
       )}
    </div>
  );
}
